dhcp-range=10.0.0.0,proxy

port=0

log-dhcp

enable-tftp
tftp-root=/boot

pxe-service=tag:!ipxe,x86-64_EFI,"pixie",ipxe.efi
pxe-service=tag:!ipxe,BC_EFI,"pixie",ipxe.efi

dhcp-match=set:ipxe,175

dhcp-boot=tag:ipxe,boot.ipxe

pxe-prompt="pixie",0
