services:
  dnsmasq:
    build: .
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./boot:/boot:ro

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./images:/usr/share/nginx/html/images:ro
      - ./autoinstall:/usr/share/nginx/html/autoinstall:ro
