url    = https://releases.ubuntu.com/26.04.1/ubuntu-26.04.1-live-server-amd64.iso
sha256 = cc8a95cde20f6ced61a322420de00f10cc3c90ced545daa46cb9c1a117f1d927

kernel = casper/vmlinuz
initrd = casper/initrd
