- name: Configure mini PCs
  hosts: minipcs
  become: true
  serial: 1
  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Remove packages no longer needed
      ansible.builtin.apt:
        autoremove: true

    - name: Install packages
      ansible.builtin.apt:
        name:
          - btop
          - neovim
          - fastfetch
        state: present

    - name: Check whether a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
