- name: Configure mini PCs
  hosts: minipcs
  become: true
  tasks:
    - name: Install btop
      ansible.builtin.apt:
        name: btop
        state: present
        update_cache: true
    - name: Install neovim
      ansible.builtin.apt:
        name: neovim
        state: present
        update_cache: true
    - name: Install fast fetch
      ansible.builtin.apt:
        name: fastfetch
        state: present
        update_cache: true
